# Get Alpine Linux
FROM node:18.12.1-alpine AS node

# Install bash, sudo, and git
RUN apk add bash \
    sudo \
    git

# change working directory
WORKDIR /angular

# copy package.json
COPY package.json ./

# copy package-lock.json
COPY package-lock.json ./

# install desired version of npm
RUN npm install -g npm@9.2.0

# Install Angular CLI
RUN npm install -g @angular/cli@15.0.1 typescript@4.8.2

# install dependencies
RUN npm install --force

# Export port 4200
EXPOSE 4200

# start app
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]